### ISSUE TITLE
Not working with henkaku enso.

### ISSUE THREAD

**Issue by PxEclipse** [rereprep/noled#1]
Greetings and thank you for the great plugin. Sadly it's not working with henkaku enso. If you have the time, could you please look into it?

Much appreciated.

**Comment by CelesteBlue-dev** [comment]
@rereprep May you compile NoLED plugin with vita-make-fself -c instead of vita-make-fself.
Enso can only load compressed plugins and executables on boot.
Later in LiveArea, not compressed plugins and executables can be loaded.
Regards.

**Comment by rereprep** [comment]
release v1.1 solves the problem, thanks to Celeste for the tip.
